FROM golang:1.22.2 AS build-stage
ENV GOCACHE=/go/pkg/mod
ENV GOMODCACHE=/gomod_cache

RUN go env -w GOCACHE=$GOCACHE
RUN go env -w GOMODCACHE=$GOMODCACHE

WORKDIR /usr/local/app

COPY go.mod go.sum ./
RUN go mod tidy
RUN --mount=type=cache,mode=0755,target=/go/pkg/mod go mod download

COPY . .
RUN --mount=type=cache,target=/gomod_cache CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/main.go

FROM alpine:3.19
ENV GOTRACEBACK=single

WORKDIR /usr/local/app

COPY --from=build-stage /usr/local/app/main .

EXPOSE 3030

CMD [ "/usr/local/app/main" ]

