FROM golang:1.22.2 AS build-stage

WORKDIR /usr/local/app

COPY go.mod go.sum ./
RUN go mod tidy
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix -ldflags="-s -w" -o main ./cmd/main.go

FROM alpine:latest

WORKDIR /usr/local/app

COPY --from=build-stage /usr/local/app/main .

EXPOSE 3030

CMD [ "/usr/local/app/main" ]

