apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: go-ddd
build:
  local:
    push: false
    concurrency: 0
  artifacts:
    - image: go-ddd
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: './**/*.go'

manifests:
  rawYaml:
    - deploy/k8s/postgres-deployment.yaml
    - deploy/k8s/postgres-service.yaml
    - deploy/k8s/configmap.yaml
    - deploy/k8s/deployment.yaml
    - deploy/k8s/service.yaml

portForward:
  - resourceType: deployment
    resourceName: go-ddd
    port: 3030
    localPort: 3030