apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: go-ddd

profiles:
  - name: dev
    # automatically activate this profile when current context is "minikube"
    activation:
      - kubeContext: minikube
      - command: dev
    build:
      local:
        push: false
        useBuildkit: true
      artifacts:
        - image: go-ddd
          ko:
            fromImage: gcr.io/distroless/base-debian11:debug
            main: ./cmd
            dependencies:
              paths:
              - "**/*.go"
              - go.*

    # manifests:
    #   rawYaml:
    #     - deploy/k8s/postgres-deployment.yaml
    #     - deploy/k8s/postgres-service.yaml
    #     - deploy/k8s/deployment.yaml
    #     - deploy/k8s/service.yaml

    deploy:
      statusCheckDeadlineSeconds: 120
      helm: # other options are kubectl
        releases:
        - name: postgres
          repo: https://charts.bitnami.com/bitnami
          remoteChart: postgresql
          version: 15.2.12
          namespace: default
          wait: true
          createNamespace: true
          setValues:
            auth.database: postgres
            auth.username: root
            auth.password: P@ssw0rd
        - name: eck
          repo: https://helm.elastic.co
          remoteChart: eck-operator
          version: 2.12.1
          namespace: elastic-system
          wait: true
          createNamespace: true
        - name: elastic
          repo: https://helm.elastic.co
          remoteChart: elasticsearch
          version: 8.5.1
          namespace: elastic-system
          setValues:
            replicas: 1
            imageTag: 8.13.4
        - name: kibana
          repo: https://helm.elastic.co
          remoteChart: kibana
          version: 8.5.1
          namespace: elastic-system
          setValues:
            replicas: 1
            imageTag: 8.13.4
        - name: go-ddd
          chartPath: deploy/helm  # path to your helm charts
          valuesFiles:
            - "deploy/helm/values.yaml"
          recreatePods: true
          version: 0.1.0

    portForward:
      - resourceType: service
        resourceName: go-ddd-helm
        port: 3030
        localPort: 3030
      - resourceType: service
        resourceName: elasticsearch-master
        namespace: elastic-system
        port: 9200
        localPort: 9200
      - resourceType: service
        resourceName: kibana-kibana
        namespace: elastic-system
        port: 5601
        localPort: 5601

  - name: prod
    build:
      artifacts:
       - image: registry.local:5500/go-ddd
         kaniko:
           dockerfile: Dockerfile.dev
      cluster: {}