apiVersion: v1
kind: ConfigMap
metadata:
  name: go-ddd-config
data:
  config.yaml: |
    log:
      level: info

    general:
      app_name: "go-ddd"
      version: "0.0.1"
      debug: true

    transport:
      http:
        host: 0.0.0.0
        port: 3030

    infrastructure:
      persistence:
        type: postgres
        table_prefix:
        postgres:
          host: postgres.default.svc.cluster.local
          port: 5432
          username: root
          password: P@ssw0rd
          db_name: postgres
      cache:
        type: memory
        delimiter: ":"
        memory:
        redis:
  model.conf: |
    [request_definition]
    r = sub, obj, act

    [policy_definition]
    p = sub, obj, act

    [role_definition]
    g = _, _

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act