apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ddd
spec:
  selector:
    matchLabels:
      app: go-ddd
  template:
    metadata:
      labels:
        app: go-ddd
    spec:
      containers:
      - name: go-ddd
        image: go-ddd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3030
