apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ddd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-ddd
  template:
    metadata:
      labels:
        app: go-ddd
    spec:
      containers:
      - name: go-ddd
        image: go-ddd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3030
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/app/config
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: go-ddd-config