transport:
  http:
    host: 0.0.0.0
    port: 3030

infrastructure:
  persistence:
    type: postgres
    table_prefix:
    postgres:
      host: 0.0.0.0
      port: 5432
      username: root
      password: P@ssw0rd
      db_name: postgres
  cache:
    type: memory
    delimiter: ":"
    memory:
    redis:
